class AppLocalizations {
  static const Map<String, String> ar = {
    'app_name': 'مسار',
    'login': 'تسجيل الدخول',
    'logout': 'تسجيل الخروج',
    'map': 'الخريطة',
    'checkpoints': 'الحواجز',
    'search': 'البحث',
    'open': 'سالك',
    'closed': 'مغلق',
    'crowded': 'أزمة',
    'north': 'شمال',
    'south': 'جنوب',
    'east': 'شرق',
    'west': 'غرب',
    'entrance': 'للداخل',
    'exit': 'للخارج',
    'in': 'للداخل',
    'out': 'للخارج',
    'soldiers': 'جيش الاحتلال',
    'vote': 'تصويت',
    'status': 'الحالة',
    'direction': 'الاتجاه',
    'comment': 'تعليق',
    'submit': 'إرسال',
    'cancel': 'إلغاء',
    'nearby_only': 'يمكنك التصويت فقط إذا كنت على بعد 3 كم من الحاجز',
    'checkpoint_details': 'تفاصيل الحاجز',
    'last_updated': 'آخر تحديث',
    'votes': 'تصويتات',
    'region': 'المنطقة',
    'select_region': 'اختر المنطقة',
    'all_regions': 'جميع المناطق',
    'ramallah': 'رام الله',
    'nablus': 'نابلس',
    'hebron': 'الخليل',
    'bethlehem': 'بيت لحم',
    'jericho': 'أريحا',
    'jenin': 'جنين',
    'tulkarm': 'طولكرم',
    'qalqilya': 'قلقيلية',
    'admin_panel': 'لوحة الإدارة',
    'add_checkpoint': 'إضافة حاجز',
    'long_press_map': 'اضغط مطولاً على الخريطة لإضافة حاجز جديد',
    'name': 'الاسم',
    'coordinates': 'الإحداثيات',
    'save': 'حفظ',
    'override_status': 'تعديل الحالة',
    'current_location': 'موقعك الحالي',
    'error_location': 'تعذر الحصول على الموقع',
    'check_internet': 'تحقق من اتصال الإنترنت',
    'no_checkpoints': 'لا توجد حواجز في هذه المنطقة',
    'minutes_ago': 'دقيقة مضت',
    'now': 'الآن',
    'vote_window_minutes': '60', 
    'settings': 'الإعدادات',
    'appearance': 'المظهر',
    'theme_system': 'تلقائي',
    'theme_light': 'فاتح',
    'theme_dark': 'داكن',
    'theme_system_hint': 'عند اختيار "تلقائي"، يتبع التطبيق إعدادات النظام.',
  };

  static String tr(String key) {
    return ar[key] ?? key;
  }
}